

const arrayFnished = [
    {
        num: '1',
        name: 'Большой шар с рисунком',
        count: '2',
        year: '1960',
        shape: 'шар',
        color: 'желтый',
        size: 'большой',
        favorite: false,
        img:"./Volumes/том/reacthome/reacthome/src/components/TreeDecoration/img/annie-spratt-zh7GEuORbUw-unsplash.jpg",
    },
    {
        num: '2',
        name: 'Большой шар с рисунком',
        count: '21',
        year: '1960',
        shape: 'шар',
        color: 'красный',
        size: 'большой',
        favorite: false,
    },
    {
        num: '3',
        name: 'Большой шар с рисунком',
        count: '22',
        year: '1960',
        shape: 'шар',
        color: 'синий',
        size: 'большой',
        favorite: false,
    },
    {
        num: '3',
        name: 'Большой шар с рисунком',
        count: '22',
        year: '1960',
        shape: 'шар',
        color: 'синий',
        size: 'большой',
        favorite: false,
    },
    {
        num: '3',
        name: 'Большой шар с рисунком',
        count: '22',
        year: '1960',
        shape: 'шар',
        color: 'синий',
        size: 'большой',
        favorite: false,
    },
    {
        num: '3',
        name: 'Большой шар с рисунком',
        count: '22',
        year: '1960',
        shape: 'шар',
        color: 'синий',
        size: 'большой',
        favorite: false,
    },
    {
        num: '3',
        name: 'Большой шар с рисунком',
        count: '22',
        year: '1960',
        shape: 'шар',
        color: 'синий',
        size: 'большой',
        favorite: false,
    },
    {
        num: '3',
        name: 'Большой шар с рисунком',
        count: '22',
        year: '1960',
        shape: 'шар',
        color: 'синий',
        size: 'большой',
        favorite: false,
    },
    {
        num: '3',
        name: 'Большой шар с рисунком',
        count: '22',
        year: '1960',
        shape: 'шар',
        color: 'синий',
        size: 'большой',
        favorite: false,
    },
]
export default arrayFnished;